"""
white_house_stylometry.py
-------------------------
Extracts stylometric (writing-style) features from scraped White House articles.
These features capture unconscious authorship signals such as sentence structure,
vocabulary richness, punctuation habits, and function-word usage.

Also includes LLM-likelihood detection — statistical heuristics that estimate
how likely each article was generated (or heavily assisted) by an AI language model.

The output CSV can be used for unsupervised clustering to identify distinct
writing styles / potential different authors.

Dependencies: nltk, textstat (same as white_house_analysis.py)
"""

import json
import os
import csv
import re
import math
import nltk
import textstat
from collections import Counter

# Ensure NLTK data is available
for resource in ['punkt', 'punkt_tab', 'averaged_perceptron_tagger', 'averaged_perceptron_tagger_eng']:
    try:
        nltk.data.find(f'tokenizers/{resource}' if 'punkt' in resource else f'taggers/{resource}')
    except LookupError:
        nltk.download(resource, quiet=True)


# ─── Feature Extraction ─────────────────────────────────────────────────────

def _tokenize_sentences(text):
    """Split text into sentences using NLTK."""
    return nltk.sent_tokenize(text)


def _tokenize_words(text):
    """Split text into words (alphabetic tokens only, lowercased)."""
    return [w.lower() for w in nltk.word_tokenize(text) if w.isalpha()]


# The 50 most common English function words — these are the strongest
# stylometric signal because writers use them unconsciously.
FUNCTION_WORDS = [
    "the", "of", "and", "to", "a", "in", "that", "is", "was", "it",
    "for", "on", "are", "as", "with", "his", "they", "be", "at", "one",
    "have", "this", "from", "or", "had", "by", "but", "not", "what", "all",
    "were", "we", "when", "your", "can", "said", "there", "each", "which", "do",
    "their", "if", "will", "up", "about", "out", "then", "them", "an", "would"
]

# Common LLM filler phrases — these appear disproportionately in AI-generated text.
# Each phrase is lowercased for matching.
LLM_FILLER_PHRASES = [
    "it is important to note",
    "it's important to note",
    "it is worth noting",
    "it's worth noting",
    "in this context",
    "in today's world",
    "in the modern era",
    "it is crucial",
    "it's crucial",
    "it is essential",
    "it's essential",
    "furthermore",
    "moreover",
    "additionally",
    "in conclusion",
    "to summarize",
    "in summary",
    "as we have seen",
    "as mentioned earlier",
    "as previously mentioned",
    "this highlights",
    "this underscores",
    "this demonstrates",
    "plays a crucial role",
    "plays a vital role",
    "plays an important role",
    "navigating the complexities",
    "navigating the landscape",
    "a testament to",
    "serves as a reminder",
    "raises important questions",
    "sheds light on",
    "paves the way for",
    "it remains to be seen",
    "only time will tell",
    "at the end of the day",
    "the fact of the matter",
    "broadly speaking",
    "taken together",
    "by and large",
    "delve into",
    "delves into",
    "a comprehensive",
    "a nuanced",
    "multifaceted",
    "a holistic",
    "leverage",
    "foster",
    "bolster",
    "underpin",
    "underpins",
]


# ─── LLM Likelihood Detection ───────────────────────────────────────────────

def detect_llm_likelihood(text, sentences, words, word_freq, total_words, total_sentences):
    """
    Estimate the likelihood that a text was generated by an LLM using
    statistical heuristics. Returns a dict of sub-scores and a composite score.
    
    Each sub-signal is normalized to 0.0-1.0 where higher = more LLM-like.
    The composite score is a weighted average of all sub-signals.
    """
    if total_sentences < 3 or total_words < 50:
        return None

    # ── 1. Sentence Length Uniformity ──
    # LLMs produce sentences with very consistent lengths.
    # Human writing has much more variance (short punchy sentences mixed with long ones).
    sent_lengths = [len(s.split()) for s in sentences]
    sent_mean = sum(sent_lengths) / len(sent_lengths)
    sent_std = math.sqrt(sum((x - sent_mean) ** 2 for x in sent_lengths) / len(sent_lengths))
    # Coefficient of variation (CV). Human text typically CV > 0.5, LLM text CV < 0.35
    sent_cv = sent_std / sent_mean if sent_mean > 0 else 0
    # Normalize: CV of 0.0 -> score 1.0, CV of 0.7+ -> score 0.0
    sentence_uniformity_score = max(0.0, min(1.0, 1.0 - (sent_cv / 0.7)))

    # ── 2. Vocabulary Predictability ──
    # LLMs use fewer rare words. Measure ratio of words appearing only 1-2 times.
    rare_words = sum(1 for w, c in word_freq.items() if c <= 2)
    rare_ratio = rare_words / len(word_freq) if word_freq else 0
    # Human text: rare_ratio typically > 0.7. LLM: < 0.55
    # Invert: lower rare ratio = more LLM-like
    vocab_predictability_score = max(0.0, min(1.0, 1.0 - ((rare_ratio - 0.4) / 0.4)))

    # ── 3. Burstiness ──
    # Human writing is "bursty" — complexity fluctuates across the text.
    # LLM text maintains consistent complexity throughout.
    # Measure by computing readability variance across chunks.
    chunk_size = max(3, total_sentences // 5)  # ~5 chunks
    chunk_complexities = []
    for j in range(0, total_sentences, chunk_size):
        chunk_sents = sentences[j:j + chunk_size]
        if not chunk_sents:
            continue
        chunk_text = " ".join(chunk_sents)
        chunk_words = [w for w in chunk_text.split() if w.isalpha()]
        if len(chunk_words) > 10:
            avg_wl = sum(len(w) for w in chunk_words) / len(chunk_words)
            chunk_complexities.append(avg_wl)

    if len(chunk_complexities) >= 2:
        burst_mean = sum(chunk_complexities) / len(chunk_complexities)
        burst_std = math.sqrt(
            sum((x - burst_mean) ** 2 for x in chunk_complexities) / len(chunk_complexities)
        )
        burst_cv = burst_std / burst_mean if burst_mean > 0 else 0
        # Low CV = low burstiness = more LLM-like
        burstiness_score = max(0.0, min(1.0, 1.0 - (burst_cv / 0.15)))
    else:
        burstiness_score = 0.5  # insufficient data, neutral

    # ── 4. Paragraph Length Regularity ──
    # LLMs tend to produce very evenly-sized paragraphs.
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    if len(paragraphs) >= 3:
        para_lengths = [len(p.split()) for p in paragraphs]
        para_mean = sum(para_lengths) / len(para_lengths)
        para_std = math.sqrt(
            sum((x - para_mean) ** 2 for x in para_lengths) / len(para_lengths)
        )
        para_cv = para_std / para_mean if para_mean > 0 else 0
        paragraph_regularity_score = max(0.0, min(1.0, 1.0 - (para_cv / 0.8)))
    else:
        paragraph_regularity_score = 0.5  # insufficient data

    # ── 5. Filler Phrase Density ──
    # Count LLM-typical filler phrases per 1000 words.
    text_lower = text.lower()
    filler_count = sum(text_lower.count(phrase) for phrase in LLM_FILLER_PHRASES)
    filler_density = (filler_count / total_words) * 1000 if total_words > 0 else 0
    # Human text: typically < 1 per 1000 words. Heavy LLM: > 5 per 1000.
    filler_score = max(0.0, min(1.0, filler_density / 5.0))

    # ── 6. Word Length Uniformity ──
    # Similar to sentence uniformity but at the word level.
    wl_list = [len(w) for w in words]
    wl_mean = sum(wl_list) / len(wl_list)
    wl_std = math.sqrt(sum((x - wl_mean) ** 2 for x in wl_list) / len(wl_list))
    wl_cv = wl_std / wl_mean if wl_mean > 0 else 0
    # Human CV typically > 0.45, LLM < 0.35
    word_length_uniformity_score = max(0.0, min(1.0, 1.0 - (wl_cv / 0.55)))

    # ── Composite Score ──
    # Weighted average — sentence uniformity and burstiness are strongest signals
    weights = {
        "sentence_uniformity": 0.25,
        "vocab_predictability": 0.15,
        "burstiness": 0.25,
        "paragraph_regularity": 0.10,
        "filler_phrase_density": 0.15,
        "word_length_uniformity": 0.10,
    }
    sub_scores = {
        "sentence_uniformity": sentence_uniformity_score,
        "vocab_predictability": vocab_predictability_score,
        "burstiness": burstiness_score,
        "paragraph_regularity": paragraph_regularity_score,
        "filler_phrase_density": filler_score,
        "word_length_uniformity": word_length_uniformity_score,
    }
    composite = sum(sub_scores[k] * weights[k] for k in weights)

    result = {}
    for k, v in sub_scores.items():
        result[f"llm_{k}"] = round(v, 4)
    result["llm_filler_count"] = filler_count
    result["llm_filler_density_per_1k"] = round(filler_density, 3)
    result["llm_likelihood_score"] = round(composite, 4)

    return result


def extract_features(text):
    """
    Extract a dictionary of stylometric features from a block of text.
    Returns None if the text is too short for meaningful analysis.
    """
    if not text or len(text.split()) < 50:
        return None

    sentences = _tokenize_sentences(text)
    words = _tokenize_words(text)
    all_tokens = nltk.word_tokenize(text)  # includes punctuation

    if not sentences or not words:
        return None

    total_words = len(words)
    total_sentences = len(sentences)
    total_chars_in_words = sum(len(w) for w in words)

    # ── Sentence-level features ──
    sentence_lengths = [len(nltk.word_tokenize(s)) for s in sentences]
    avg_sentence_length = sum(sentence_lengths) / total_sentences
    std_sentence_length = math.sqrt(
        sum((sl - avg_sentence_length) ** 2 for sl in sentence_lengths) / total_sentences
    ) if total_sentences > 1 else 0.0

    # ── Word-level features ──
    avg_word_length = total_chars_in_words / total_words
    word_lengths = [len(w) for w in words]
    std_word_length = math.sqrt(
        sum((wl - avg_word_length) ** 2 for wl in word_lengths) / total_words
    ) if total_words > 1 else 0.0

    # ── Vocabulary richness ──
    word_freq = Counter(words)
    unique_words = len(word_freq)
    type_token_ratio = unique_words / total_words

    # Hapax legomena: words that appear exactly once (high = rich vocabulary)
    hapax_legomena = sum(1 for w, c in word_freq.items() if c == 1)
    hapax_ratio = hapax_legomena / total_words

    # Yule's K measure of vocabulary richness (lower = richer vocabulary)
    freq_of_freqs = Counter(word_freq.values())
    m1 = total_words
    m2 = sum(i * i * freq for i, freq in freq_of_freqs.items())
    yules_k = 10000 * (m2 - m1) / (m1 * m1) if m1 > 0 else 0.0

    # ── Punctuation features (per 1000 words) ──
    punct_counts = Counter(t for t in all_tokens if not t.isalnum())
    per_k = 1000 / total_words if total_words > 0 else 0

    comma_rate = punct_counts.get(",", 0) * per_k
    semicolon_rate = punct_counts.get(";", 0) * per_k
    colon_rate = punct_counts.get(":", 0) * per_k
    exclamation_rate = punct_counts.get("!", 0) * per_k
    question_rate = punct_counts.get("?", 0) * per_k
    dash_rate = (punct_counts.get("—", 0) + punct_counts.get("--", 0)) * per_k
    ellipsis_rate = punct_counts.get("...", 0) * per_k

    # ── Function word ratios ──
    function_word_features = {}
    for fw in FUNCTION_WORDS:
        function_word_features[f"fw_{fw}"] = word_freq.get(fw, 0) / total_words

    # ── Passive voice ratio ──
    # Approximate: count "was/were/been/being + past participle (VBN)"
    try:
        tagged = nltk.pos_tag(nltk.word_tokenize(text[:5000]))  # limit for speed
        passive_count = 0
        for i in range(1, len(tagged)):
            if tagged[i][1] == "VBN" and tagged[i - 1][0].lower() in ("was", "were", "been", "being", "is", "are", "be"):
                passive_count += 1
        passive_voice_ratio = passive_count / total_sentences
    except Exception:
        passive_voice_ratio = 0.0

    # ── Readability (already used in main analysis, but useful for clustering) ──
    flesch_kincaid_grade = textstat.flesch_kincaid_grade(text)
    flesch_reading_ease = textstat.flesch_reading_ease(text)

    # ── Paragraph structure ──
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    avg_paragraph_length = len(words) / len(paragraphs) if paragraphs else 0

    # ── Capitalization rate (can indicate shouting/emphasis style) ──
    all_alpha_tokens = [t for t in all_tokens if t.isalpha()]
    all_caps_words = sum(1 for t in all_alpha_tokens if t.isupper() and len(t) > 1)
    caps_rate = all_caps_words / len(all_alpha_tokens) if all_alpha_tokens else 0.0

    # ── Build the result ──
    features = {
        "total_words": total_words,
        "total_sentences": total_sentences,
        "avg_sentence_length": round(avg_sentence_length, 3),
        "std_sentence_length": round(std_sentence_length, 3),
        "avg_word_length": round(avg_word_length, 3),
        "std_word_length": round(std_word_length, 3),
        "type_token_ratio": round(type_token_ratio, 5),
        "hapax_ratio": round(hapax_ratio, 5),
        "yules_k": round(yules_k, 3),
        "comma_rate": round(comma_rate, 3),
        "semicolon_rate": round(semicolon_rate, 3),
        "colon_rate": round(colon_rate, 3),
        "exclamation_rate": round(exclamation_rate, 3),
        "question_rate": round(question_rate, 3),
        "dash_rate": round(dash_rate, 3),
        "ellipsis_rate": round(ellipsis_rate, 3),
        "passive_voice_ratio": round(passive_voice_ratio, 5),
        "flesch_kincaid_grade": round(flesch_kincaid_grade, 2),
        "flesch_reading_ease": round(flesch_reading_ease, 2),
        "avg_paragraph_length": round(avg_paragraph_length, 3),
        "caps_rate": round(caps_rate, 5),
    }

    # Add function word ratios
    for key, val in function_word_features.items():
        features[key] = round(val, 6)

    # ── LLM Likelihood Features ──
    llm_features = detect_llm_likelihood(
        text, sentences, words, word_freq, total_words, total_sentences
    )
    if llm_features:
        features["llm_analysis_viable"] = True
        features.update(llm_features)
    else:
        # Ensure LLM columns are always present, even if we can't compute them
        features["llm_analysis_viable"] = False
        for key in [
            "llm_sentence_uniformity", "llm_vocab_predictability",
            "llm_burstiness", "llm_paragraph_regularity",
            "llm_filler_phrase_density", "llm_word_length_uniformity",
            "llm_filler_count", "llm_filler_density_per_1k",
            "llm_likelihood_score"
        ]:
            features[key] = None

    return features


# ─── Main Pipeline ───────────────────────────────────────────────────────────

def analyze_stylometry(bronze_dir, silver_path):
    """
    Reads JSON articles from the bronze data lake directory,
    extracts stylometric features from each, and saves results to CSV.
    """
    if not os.path.exists(bronze_dir):
        print(f"Bronze directory not found: {bronze_dir}")
        return

    results = []
    filenames = sorted(f for f in os.listdir(bronze_dir) if f.endswith(".json"))
    print(f"Found {len(filenames)} JSON files to process.")

    for i, filename in enumerate(filenames, 1):
        filepath = os.path.join(bronze_dir, filename)

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                article = json.load(f)
        except Exception as e:
            print(f"  Error reading {filename}: {e}")
            continue

        content = article.get("content", "")
        title = article.get("title", "")
        date = article.get("date", "")
        category = article.get("category", "")

        if not content or len(content.split()) < 50:
            print(f"  [{i}/{len(filenames)}] Skipping (too short): {title[:50]}")
            continue

        print(f"  [{i}/{len(filenames)}] Extracting features: {title[:50]}...")

        # Clean boilerplate from beginning of content
        clean_content = content.strip()
        for boilerplate in [category, title, date]:
            if boilerplate and boilerplate in clean_content[:300]:
                clean_content = clean_content.replace(boilerplate, "", 1).strip()

        features = extract_features(clean_content)

        if features is None:
            print(f"    -> Could not extract features (text too short after cleaning)")
            continue

        # Prepend article metadata
        row = {
            "source_file": filename,
            "title": title,
            "date": date,
            "category": category,
        }
        row.update(features)
        results.append(row)

    # ── Save to CSV ──
    silver_dir = os.path.dirname(silver_path)
    os.makedirs(silver_dir, exist_ok=True)

    if results:
        keys = results[0].keys()
        with open(silver_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(results)
    else:
        with open(silver_path, "w", encoding="utf-8") as f:
            pass

    print(f"\nStylometry complete. Results saved to {silver_path}")
    print(f"Processed {len(results)} articles with {len(results[0]) if results else 0} features each.")


if __name__ == "__main__":
    bronze_dir = os.path.join(os.getcwd(), ".data_lake", "01_Bronze", "white_house")
    silver_path = os.path.join(os.getcwd(), ".data_lake", "02_Silver", "white_house", "stylometry_features.csv")

    analyze_stylometry(bronze_dir, silver_path)
